/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadaccident;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


public class Accident_Table extends javax.swing.JFrame {

    /**
     * Creates new form Accident_Table
     */
    public Accident_Table() {
        initComponents();
        
           try {
            String url = "jdbc:mysql://localhost:3306/road_accident";
            String user = "root";
            String password = "";
            Connection conn = (Connection) DriverManager.getConnection(url, user, password);

            //DefaultTableModel model = (DefaultTableModel) Reason_Table.getModel();
            DefaultTableModel model=(DefaultTableModel)accident_table.getModel();
            String query2 = " SELECT * from accident ";

            PreparedStatement preparedStmt2 = conn.prepareStatement(query2);
            preparedStmt2.execute();
            ResultSet rs2 = preparedStmt2.getResultSet();



            while (rs2.next()) {
               
               // model.addRow(new Object[]{rs2.getInt("reason_id"),rs2.getString("reason_name")});
             model.addRow(new Object[]{rs2.getInt("accident_no"),rs2.getString("date"),rs2.getInt("time_id"),rs2.getInt("location_id"),rs2.getInt("type_id"),rs2.getInt("reason_id"),rs2.getInt("season_id"),rs2.getInt("injured"),rs2.getInt("killed")});
             
            }
            conn.close();
        } catch (SQLException | HeadlessException ex) {
            //System.out.println("Welcome");
            System.out.println(ex);

        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        accident_table = new javax.swing.JTable();
        act_bt1 = new javax.swing.JButton();
        act_bt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accident_table.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        accident_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "accident no", "date", "time_id", "location_id", "type_id", "reason_id", "season_id", "injured", "killed"
            }
        ));
        jScrollPane1.setViewportView(accident_table);

        act_bt1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        act_bt1.setText("Back");
        act_bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act_bt1ActionPerformed(evt);
            }
        });

        act_bt2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        act_bt2.setText("Back To Main Page");
        act_bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act_bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(act_bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(act_bt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(act_bt1)
                        .addGap(37, 37, 37)
                        .addComponent(act_bt2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void act_bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act_bt2ActionPerformed
    
        
          setVisible(false);
      Login l=new Login();
        l.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_act_bt2ActionPerformed

    private void act_bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act_bt1ActionPerformed
        // TODO add your handling code here:
        
          setVisible(false);
      Accident ac=new Accident();
        ac.setVisible(true);
    }//GEN-LAST:event_act_bt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accident_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accident_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accident_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accident_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accident_Table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accident_table;
    private javax.swing.JButton act_bt1;
    private javax.swing.JButton act_bt2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
