/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadaccident;

import com.sun.org.apache.xpath.internal.operations.String;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;


public class S_info extends javax.swing.JFrame {

    /**
     * Creates new form S_info
     */
    public S_info() {
        initComponents();
        getContentPane().setBackground(new Color(204,204,255));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        y_b = new javax.swing.JButton();
        t_b = new javax.swing.JButton();
        v_b = new javax.swing.JButton();
        p_v = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        y_b.setBackground(new java.awt.Color(153, 255, 255));
        y_b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        y_b.setText("Year");
        y_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_bActionPerformed(evt);
            }
        });

        t_b.setBackground(new java.awt.Color(204, 255, 204));
        t_b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_b.setText("Time");
        t_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_bActionPerformed(evt);
            }
        });

        v_b.setBackground(new java.awt.Color(255, 204, 204));
        v_b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v_b.setText("Vehicle");
        v_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_bActionPerformed(evt);
            }
        });

        p_v.setBackground(new java.awt.Color(0, 204, 153));
        p_v.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p_v.setText("Place");
        p_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_vActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y_b, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v_b, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_b, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_v, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(y_b, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(t_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_b, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_v, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        S_info_time_table t=new S_info_time_table();
        t.setVisible(true);
        
    }//GEN-LAST:event_t_bActionPerformed

    private void y_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_bActionPerformed
        // TODO add your handling code here:
        setVisible(true);
        
//        Year_Table y=new Year_Table();
//        y.setVisible(true);
      CreateBar cc = new CreateBar("Statistical Information Of Road Accident", "Road Accident");
       cc.pack();
       cc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       RefineryUtilities.centerFrameOnScreen(cc);
       cc.setVisible(true);
    }//GEN-LAST:event_y_bActionPerformed

    private void p_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_vActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        S_info_place_table sp=new S_info_place_table();
        sp.setVisible(true);
        
    }//GEN-LAST:event_p_vActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home_Page h=new Home_Page();
        h.setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void v_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_bActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        S_info_vehicle_table v=new S_info_vehicle_table();
        v.setVisible(true);
        
    }//GEN-LAST:event_v_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_info().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton p_v;
    private javax.swing.JButton t_b;
    private javax.swing.JButton v_b;
    private javax.swing.JButton y_b;
    // End of variables declaration//GEN-END:variables
}
