/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadaccident;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


public class S_info_time_09_table extends javax.swing.JFrame {

    /**
     * Creates new form S_info_time_09_table
     */
    public S_info_time_09_table() {
        initComponents();
        
         try{
        String url="jdbc:mysql://localhost:3306/road_accident";
        String user="root";
        String pass="";
        
        Connection conn=(Connection)DriverManager.getConnection(url, user, pass);
        
        DefaultTableModel model=(DefaultTableModel)s_info_time_09_table.getModel();
        
        String query="SELECT a.time,count(b.accident_no) as total_accident FROM accident b left join day_time a on a.time_id=b.time_id where b.date between '09-1-1' and '09-12-31' group by a.time_id";
        PreparedStatement preparedStm=conn.prepareStatement(query);
        preparedStm.execute();
        ResultSet rs2=preparedStm.getResultSet();
        
        while(rs2.next())
        {
        
            model.addRow(new Object[]{ rs2.getString("time"),rs2.getString("total_accident") });
            
        }
        
        }
        catch(SQLException |HeadlessException e)
        {
        System.out.println(e);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        s_info_time_09_table = new javax.swing.JTable();
        t_9_b1 = new javax.swing.JButton();
        t_9_b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        s_info_time_09_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s_info_time_09_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time of The Day", "Total Number Of Accident"
            }
        ));
        jScrollPane1.setViewportView(s_info_time_09_table);

        t_9_b1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        t_9_b1.setText("Back");
        t_9_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_9_b1ActionPerformed(evt);
            }
        });

        t_9_b2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        t_9_b2.setText("Back To The Main Page ");
        t_9_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_9_b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_9_b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_9_b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(t_9_b1)
                        .addGap(35, 35, 35)
                        .addComponent(t_9_b2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_9_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_9_b1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time st=new S_info_time();
        st.setVisible(true);
    }//GEN-LAST:event_t_9_b1ActionPerformed

    private void t_9_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_9_b2ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info st=new S_info();
        st.setVisible(true);
    }//GEN-LAST:event_t_9_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_info_time_09_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_info_time_09_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_info_time_09_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_info_time_09_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_info_time_09_table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable s_info_time_09_table;
    private javax.swing.JButton t_9_b1;
    private javax.swing.JButton t_9_b2;
    // End of variables declaration//GEN-END:variables
}
