/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadaccident;

import java.awt.Color;


public class S_info_time extends javax.swing.JFrame {

    /**
     * Creates new form S_info_time
     */
    public S_info_time() {
        initComponents();
        getContentPane().setBackground(new Color(204,204,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_2007 = new javax.swing.JButton();
        t_08 = new javax.swing.JButton();
        t_09 = new javax.swing.JButton();
        t_10 = new javax.swing.JButton();
        t_11 = new javax.swing.JButton();
        t_12 = new javax.swing.JButton();
        t_13 = new javax.swing.JButton();
        t_14 = new javax.swing.JButton();
        t_15 = new javax.swing.JButton();
        t_16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        t_2007.setBackground(new java.awt.Color(0, 204, 204));
        t_2007.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_2007.setText("2007");
        t_2007.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_2007ActionPerformed(evt);
            }
        });

        t_08.setBackground(new java.awt.Color(0, 204, 204));
        t_08.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_08.setText("2008");
        t_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_08ActionPerformed(evt);
            }
        });

        t_09.setBackground(new java.awt.Color(0, 204, 204));
        t_09.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_09.setText("2009");
        t_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_09ActionPerformed(evt);
            }
        });

        t_10.setBackground(new java.awt.Color(0, 204, 204));
        t_10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_10.setText("2010");
        t_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_10ActionPerformed(evt);
            }
        });

        t_11.setBackground(new java.awt.Color(0, 204, 204));
        t_11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_11.setText("2011");
        t_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_11ActionPerformed(evt);
            }
        });

        t_12.setBackground(new java.awt.Color(0, 204, 204));
        t_12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_12.setText("2012");
        t_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_12ActionPerformed(evt);
            }
        });

        t_13.setBackground(new java.awt.Color(0, 204, 204));
        t_13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_13.setText("2013");
        t_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_13ActionPerformed(evt);
            }
        });

        t_14.setBackground(new java.awt.Color(0, 204, 204));
        t_14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_14.setText("2014");
        t_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_14ActionPerformed(evt);
            }
        });

        t_15.setBackground(new java.awt.Color(0, 204, 204));
        t_15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_15.setText("2015");
        t_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_15ActionPerformed(evt);
            }
        });

        t_16.setBackground(new java.awt.Color(0, 204, 204));
        t_16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_16.setText("2016");
        t_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_16ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     PLEASE SELECT A YEAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_15, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_13, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t_14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_2007, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_08, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_09, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_12, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_2007, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_08, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_09, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_10ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_10_table t7=new S_info_time_10_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_10ActionPerformed

    private void t_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_11ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_11_table t11=new S_info_time_11_table();
        t11.setVisible(true);
    }//GEN-LAST:event_t_11ActionPerformed

    private void t_2007ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_2007ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_table t7=new S_info_time_table();
        t7.setVisible(true);
        
    }//GEN-LAST:event_t_2007ActionPerformed

    private void t_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_08ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_08_table t7=new S_info_time_08_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_08ActionPerformed

    private void t_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_09ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_09_table t09=new S_info_time_09_table();
        t09.setVisible(true);
    }//GEN-LAST:event_t_09ActionPerformed

    private void t_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_12ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_12_table t7=new S_info_time_12_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_12ActionPerformed

    private void t_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_13ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        S_info_time_13_table t7=new S_info_time_13_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_13ActionPerformed

    private void t_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_14ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        S_info_time_14_table t7=new S_info_time_14_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_14ActionPerformed

    private void t_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_15ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
          S_info_time_15_table t7=new S_info_time_15_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_15ActionPerformed

    private void t_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_16ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
          S_info_time_16_table t7=new S_info_time_16_table();
        t7.setVisible(true);
    }//GEN-LAST:event_t_16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         setVisible(false);
          S_info t=new S_info();
        t.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_info_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_info_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_info_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_info_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_info_time().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton t_08;
    private javax.swing.JButton t_09;
    private javax.swing.JButton t_10;
    private javax.swing.JButton t_11;
    private javax.swing.JButton t_12;
    private javax.swing.JButton t_13;
    private javax.swing.JButton t_14;
    private javax.swing.JButton t_15;
    private javax.swing.JButton t_16;
    private javax.swing.JButton t_2007;
    // End of variables declaration//GEN-END:variables
}
