/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadaccident;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.naming.spi.DirStateFactory;
import javax.swing.table.DefaultTableModel;


public class S_info_time_table extends javax.swing.JFrame {

    /**
     * Creates new form S_info_time_table
     */
    public S_info_time_table() {
        initComponents();
        
         int i;
        int start_year=2007;
        Calendar now = Calendar.getInstance();   
         int current_year = now.get(Calendar.YEAR);
        
        
        
         try{
            
        String url="jdbc:mysql://localhost:3306/road_accident";
        String user="root";
        String pass="";
        
        Connection conn=(Connection)DriverManager.getConnection(url, user, pass);
        DefaultTableModel model=(DefaultTableModel)s_info_time_table.getModel();
        
        
        String query="Select count(time_id) as total from  day_time";
        PreparedStatement prepareStm=conn.prepareStatement(query);
        prepareStm.execute();
        ResultSet rs2=prepareStm.getResultSet();
        int no_of_time = 0;
        
        while(rs2.next())
        {
            no_of_time = rs2.getInt("total");
        
        }
        
        
        
         for(int j = 1; j<=no_of_time;j++ )
        
        for(i=start_year;i<current_year;i++)
             {
                 
        String query1="Select a.time ,count(b.accident_no) as total_accident from day_time a left join  accident b on a.time_id=b.time_id  where b.time_id='"+j+"' and date like'"+i+"%'";
        
        
            prepareStm=conn.prepareStatement(query1);
           prepareStm.execute();
           rs2=prepareStm.getResultSet();
           
        
            while(rs2.next())
                {
                    model.addRow(new Object[]{i,rs2.getString("a.time"),rs2.getString("total_accident")});
        
                }
        
           }
        }
        
        
        
        
        
        
        catch(SQLException |HeadlessException e)
        {
        System.out.println(e);
        }
         
         
         
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        s_info_time_table = new javax.swing.JTable();
        t_7_b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        s_info_time_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s_info_time_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Time Of The Day", "Total Number Of Accident"
            }
        ));
        jScrollPane1.setViewportView(s_info_time_table);

        t_7_b1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        t_7_b1.setText("Back");
        t_7_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_7_b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(t_7_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(t_7_b1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_7_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_7_b1ActionPerformed

        // TODO add your handling code here:
        setVisible(false);
        S_info s=new S_info();
        s.setVisible(true);
    }//GEN-LAST:event_t_7_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_info_time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_info_time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_info_time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_info_time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_info_time_table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable s_info_time_table;
    private javax.swing.JButton t_7_b1;
    // End of variables declaration//GEN-END:variables
}
